services:
  web:
    profiles:
      - ci
    networks:
      - ryoko
    depends_on:
      database:
        condition: service_healthy
      flyway:
        condition: service_completed_successfully
    build: 
      dockerfile: local.dockerfile
    ports:
      - 8000:8000
      - 8443:8443
      - 30000:30000
    volumes:
      - ./ryoko-api/target:/app
    environment:
      - SPRING_PROFILES_ACTIVE=ci
    env_file:
      - path: .env.ci
        required: false
  database:
    profiles:
      - ci
      - local
    image: postgres:16.3
    networks:
      - ryoko
    ports: 
      - 5432:5432
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: 
        - CMD-SHELL
        - pg_isready -U ryoko-user -d ryokodb
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
  flyway:
    profiles:
      - ci
      - local
    image: flyway/flyway
    networks:
      - ryoko
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/conf/flyway.toml:/flyway/conf/flyway.toml
    depends_on:
      database:
        condition: service_healthy
    command: "-configFiles=/flyway/conf/flyway.toml -url=${FLYWAY_DB_URL} -user=${DB_USERNAME} -password=${DB_PASSWORD} -connectRetries=10 migrate"

volumes:
  pgdata: null
networks:
  ryoko:
    driver: bridge