FROM amazoncorretto:21.0.6

USER root
RUN apt-get update \
    && apt-get upgrade \
    && apt-get clean \ 
    && rm -rf /var/lib/apt/lists/*

USER 1000

EXPOSE 8000
EXPOSE 8443
EXPOSE 30000

COPY --chown=appuser:appuser ./docker/*.sh /home/appuser/bin
WORKDIR /app

ENTRYPOINT ["bash", "/home/appuser/bin/entrypoint-local.sh"]