---
spring:
  main:
    banner-mode: CONSOLE
  datasource:
    url: "${DB_URL}"
    username: "${DB_USERNAME}"
    password: "${DB_PASSWORD}"
server:
  port: 30000
  ssl:
    enabled: false
management:
  endpoints:
    web:
      exposure:
        include: env
  endpoint:
    env:
      show-values: ALWAYS
springdoc:
  show-actuator: true